[general]
import = [
	"~/.config/alacritty/kanagawa.toml"
]

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
size = 10

[window]
dimensions = { columns = 120, lines = 40 }
padding = {x = 4, y = 4}
dynamic_title = false
